export const GET_ARTICLES = 'GET_ARTICLES'
export const GET_ARTICLE_BY_CATEGORIES = 'GET_ARTICLE_BY_CATEGORIES'
export const GET_MORE_ARTICLE_BY_CATEGORIES =
    'GET_MORE_ARTICLE_BY_CATEGORIES'

export const GET_MORE_ARTICLES = 'GET_MORE_ARTICLES'
export const GET_ARTICLE_CATEGORIES = 'GET_ARTICLE_CATEGORIES'

export const OTP_REQUEST = 'OTP_REQUEST'
export const OTP_VERIFICATION_SUCCESS = 'OTP_VERIFICATION_SUCCESS'
export const OTP_VERIFICATION_FAILURE = 'OTP_VERIFICATION_FAILURE'

export const USER_LOGGED_OUT = 'USER_LOGGED_OUT'
